### ISSUE TITLE
Documentation update request: creating PostgreSQL user & DB.

### ISSUE THREAD

**Issue by janzankowski** [OpenUpSA/indigo#117]
**Environment:**

Ubuntu 16.04

**Steps to reproduce:**

Executing the following commands given in the documentation doesn't work.

1. `sudo su - postgres createuser -d -P indigo` results in:

<pre>
(env) jan@cuyp:~/Code/indigo2$ sudo su - postgres createuser -d -P indigo
[sudo] password for jan: 
su: invalid option -- 'd'
Usage: su [options] [LOGIN]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                make the shell a login shell
  -m, -p,
  --preserve-environment        do not reset environment variables, and
                                keep the same shell
  -s, --shell SHELL             use SHELL instead of the default in passwd
</pre>

2. `sudo su - postgres createdb indigo` results in:

<pre>
(env) jan@cuyp:~/Code/indigo2$ sudo su - postgres createdb indigo
/usr/bin/createdb: line 19: use: command not found
/usr/bin/createdb: line 20: use: command not found
/usr/bin/createdb: line 21: use: command not found
/usr/bin/createdb: createdb: line 23: syntax error near unexpected token `$version,'
/usr/bin/createdb: createdb: line 23: `my ($version, $cluster, $db, $port, $host);'
</pre>

**How to fix:**

Update the documentation as follows: 

- `sudo su - postgres -c 'createuser -d -P indigo'`
- `sudo su - postgres -c 'createdb indigo'`

**Comment by longhotsummer** [comment]
@goose-life you hit this same issue, I think. @janzankowski's suggestion is a good fix -- would you be able to update the README when you get a chance?
